### ISSUE TITLE
Incompatibility with Craft CMS 4.10.2

### ISSUE THREAD

**Issue by illiterati** [jimstrike/craft-intercom-messenger#1]
Hi there. We just updated our Craft CMS installation to 4.10.2, and the front end of the website fails. We can still access the back-end, and if logged in while viewing the front end, we get this error:

`Class "craft\enums\CmsEdition" not found`

Disabling this plug-in allowed the site to operate again.

**Comment by ryssbowh** [comment]
Same problem here

**Comment by jimstrike** [comment]
@illiterati @ryssbowh 
The issue has been fixed. Please update the plugin to the latest version. Consider as well updating Craft to the latest version. Sorry for the late response. Let me know if you are still having issues.
